package com.smarttransit.smart_transit.notification;

public enum NotificationType {
	BOOKING_CONFIRMED, BOOKING_CANCELLED, BOOKING_EXPIRED, PAYMENT_SUCCEEDED, PAYMENT_FAILED, REFUND_ISSUED,
	JOURNEY_REMINDER, SCHEDULE_CHANGE, DELAY, SERVICE_ALERT
}
